### ISSUE TITLE
compile on archlinux

### ISSUE THREAD

**Issue by openmotion** [mikeferguson/libam7xxx#1]
hello 
when i compile in archlinux i have this error :
[-Wdeprecated-declarations]
    av_free_packet(&out_packet);
    ^~~~~~~~~~~~~~
In file included from /usr/include/libavformat/avformat.h:319:0,
                 from /usr/include/libavdevice/avdevice.h:51,
                 from /home/xxx/Desktop/libam/libam7xxx-debian-ubuntu/examples/am7xxx-play.c:32:
/usr/include/libavcodec/avcodec.h:4650:6: note: déclaré ici
 void av_free_packet(AVPacket *pkt);
      ^~~~~~~~~~~~~~
/home/xxx/Desktop/libam/libam7xxx-debian-ubuntu/examples/am7xxx-play.c:445:3: warning: « av_free_packet » est obsolète [-Wdeprecated-declarations]
   av_free_packet(&in_packet);
   ^~~~~~~~~~~~~~
In file included from /usr/include/libavformat/avformat.h:319:0,
                 from /usr/include/libavdevice/avdevice.h:51,
                 from /home/xxx/Desktop/libam/libam7xxx-debian-ubuntu/examples/am7xxx-play.c:32:
/usr/include/libavcodec/avcodec.h:4650:6: note: déclaré ici
 void av_free_packet(AVPacket *pkt);
      ^~~~~~~~~~~~~~
make[2]: *** [examples/CMakeFiles/am7xxx-play.dir/build.make:63: examples/CMakeFiles/am7xxx-play.dir/am7xxx-play.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:248: examples/CMakeFiles/am7xxx-play.dir/all] Error 2

my version of ffmpeg is : 
ffmpeg version 3.4.2

**Comment by mikeferguson** [comment]
Honestly, this is ancient code -- I had a hard time getting it to work on Ubuntu 12.04 years ago. I haven't worked with it since (no longer have the projector).
