### ISSUE TITLE
Do you have a copy of the PDF datasheet  ?

### ISSUE THREAD

**Issue by maaaaz** [mikeferguson/libam7xxx#2]
Hello @mikeferguson,

Do you have a copy of the datasheet PDF you point there: http://wenku.baidu.com/view/543c8b4d852458fb770b56ee.html ?

The link kind of limit reading to the first page !

Cheers.

**Comment by mikeferguson** [comment]
I don't have a PDF of this (heck, I don't even have the projector anymore - this code is 11 years old)
